services:
  library-backend :
    build :
      context : .
      dockerfile : Dockerfile
    image: library-backend:latest
    ports:
      - "3000:3000"
    networks:
      - postgres-db




networks:
  postgres-db :
    external: true
    name: postgres-db